// src/app/videoUI/playlistUI.component.ts
import { Component, OnInit, SecurityContext } from '@angular/core'; 
import { ActivatedRoute } from '@angular/router'
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  templateUrl: './playlistUI.component.html',
  selector: 'playlist-ui',
})
export class PlaylistUI implements OnInit {
  constructor(
    private route: ActivatedRoute,
    private sanitizer: DomSanitizer
    ) {}

  isValid: boolean;
  safeUrl: SafeResourceUrl;

  ngOnInit() {
    this.route.queryParams.subscribe(parameters => {
      if (parameters['listUrl']) {
        let baseEmbedUrl: String = "https://www.youtube.com/embed/videoseries?list=";
        this.safeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(baseEmbedUrl + parameters['listUrl']);
        this.isValid = true;
      }
    });
  }
}
<div *ngIf="isValid">
    <iframe id="player" type="text/html" [src]="safeUrl" allow="autoplay; encrypted-media" autoplay="1" frameborder="0">
    </iframe>
</div>

// ytgbvui/src/views/PlaylistUI.vue
<template>
  <div>
    <iframe id="player" type="text/html" :src="completeLink" allow="autoplay; encrypted-media" autoplay="1" frameborder="0">
    </iframe>
  </div>
</template>

<script>
export default {
  name: "PlaylistUI",
  props: {
    playlistId: String
  },
  data: function() {
    return {
      completeLink: "https://www.youtube.com/embed/videoseries?list=" + this.playlistId
    }
  }
}
</script>

<style scoped>
  iframe, div {
    width: 100vw;
    height: 100vh;
  }
</style>
